{
  "comments": [
    {
      "key": {
        "uuid": "1acb0d3e_9e3c7c95",
        "filename": "sfc/lib/utils.py",
        "patchSetId": 3
      },
      "lineNbr": 33,
      "author": {
        "id": 4393
      },
      "writtenOn": "2017-02-07T10:22:38Z",
      "side": 1,
      "message": "just curious: is stdin needed?",
      "range": {
        "startLine": 33,
        "startChar": 28,
        "endLine": 33,
        "endChar": 29
      },
      "revId": "1681e41df34d1617bbced41b98e23a9cb64a0d25",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1acb0d3e_5e461425",
        "filename": "sfc/lib/utils.py",
        "patchSetId": 3
      },
      "lineNbr": 41,
      "author": {
        "id": 4393
      },
      "writtenOn": "2017-02-07T10:22:38Z",
      "side": 1,
      "message": "I think that, in case of failure, it would be useful to log the command itself, with a \"FAILED\" message. Otherwise, if the command just returns something !\u003d 0 but nothing to stderr, it is difficult to debug.",
      "range": {
        "startLine": 41,
        "startChar": 8,
        "endLine": 41,
        "endChar": 14
      },
      "revId": "1681e41df34d1617bbced41b98e23a9cb64a0d25",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}