{
  "comments": [
    {
      "key": {
        "uuid": "1a494da4_d9f804e8",
        "filename": "sfc/lib/config.py",
        "patchSetId": 2
      },
      "lineNbr": 13,
      "author": {
        "id": 3405
      },
      "writtenOn": "2018-05-30T08:25:13Z",
      "side": 1,
      "message": "wrong order. os should be right after logging.",
      "revId": "bcf291b71ee625126331b07a1e7f80c01f1bc789",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}